### ISSUE TITLE
webpack build

### ISSUE THREAD

**Issue by kofifus** [chafey/cornerstone#120]
I can't find instruction on building the latest sources (webpack version)

what packages are needed and what is the build process ?

Thx!

**Comment by jpambrun** [comment]
I did ```yarn install``` then ```yarn build```.
```cat packages.json``` givies you a list of options under ```"scripts"```.

JF

**Comment by kofifus** [comment]
OK it would be great to have a build document .. especially for those like me new to yarn etc

I installed yarn, shx, karma, karma-phantomjs-launcher

OK I installed yarn (new to all this), then went to the node_modules\cornerstone-wado-image-loader directory and did 'yarn build'

I get:

```
C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader>yarn build
yarn build v0.24.5
$ npm run clean:dist && npm run build:es6 && npm run build:codecs

> cornerstone-wado-image-loader@0.14.4 clean:dist C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader
> shx rm -rf dist


> cornerstone-wado-image-loader@0.14.4 build:es6 C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader
> npm run test && npm run version && npm run webpack && npm run doc:generate


> cornerstone-wado-image-loader@0.14.4 test C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader
> npm run test:phantom


> cornerstone-wado-image-loader@0.14.4 test:phantom C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader
> karma start config/karma/karma-phantom.js

23 05 2017 10:04:24.567:ERROR [config]: Error in config file!
 TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.resolve (path.js:186:7)
    at Object.<anonymous> (C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader\config\webpack\webpack-base.js:3:22)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader\config\webpack\webpack-dev.js:1:80)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test:phantom"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cornerstone-wado-image-loader@0.14.4 test:phantom: `karma start config/karma/karma-phantom.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cornerstone-wado-image-loader@0.14.4 test:phantom script 'karma start config/karma/karma-phantom.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cornerstone-wado-image-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     karma start config/karma/karma-phantom.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cornerstone-wado-image-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cornerstone-wado-image-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cornerstone-wado-image-loader@0.14.4 test: `npm run test:phantom`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cornerstone-wado-image-loader@0.14.4 test script 'npm run test:phantom'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cornerstone-wado-image-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test:phantom
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cornerstone-wado-image-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cornerstone-wado-image-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:es6"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! cornerstone-wado-image-loader@0.14.4 build:es6: `npm run test && npm run version && npm run webpack && npm run doc:generate`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cornerstone-wado-image-loader@0.14.4 build:es6 script 'npm run test && npm run version && npm run webpack && npm run doc:generate'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cornerstone-wado-image-loader package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run test && npm run version && npm run webpack && npm run doc:generate
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs cornerstone-wado-image-loader
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls cornerstone-wado-image-loader
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\src\WamiPACS 3.x\ZeroFP\node_modules\cornerstone-wado-image-loader\npm-debug.log
error Command failed with exit code 1.

```
